version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 10
  identical-code:
    config:
      threshold: 10
exclude_patterns:
- "doc/"
- "examples/"
- "images/"
- "resources/"