builds:
  -
    main: ./cmd/amass/main.go
    binary: amass
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386

  -
    main: ./cmd/amass.netdomains/main.go
    binary: amass.netdomains
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386

  -
    main: ./cmd/amass.viz/main.go
    binary: amass.viz
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386

  -
    main: ./cmd/amass.db/main.go
    binary: amass.db
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386

  -
    main: ./cmd/amass.tracker/main.go
    binary: amass.tracker
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386

archive:
  name_template: "amass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macos
    386: i386
  wrap_in_directory: true
  format: zip
  files:
    - LICENSE
    - README.md
    - wordlists/*

checksum:
  name_template: "amass_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'
