project_name: amass

before:
  hooks:
  - go mod download

builds:
  -
    main: ./cmd/amass/
    binary: amass
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - README.md
      - examples/config.ini

sboms:
  - documents:
      - "{{ .Binary }}_{{ .Os }}_{{ .Arch }}.bom.json"
    artifacts: binary
    cmd: cyclonedx-gomod
    env:
      - GOOS={{ .Os }}
      - GOARCH={{ .Arch }}
    args: [ "app", "-main", "cmd/amass", "-licenses", "-packages", "-json", "-output", "$document", "$PWD" ]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: OWASP
    name: Amass

brews:
  -
    name: amass
    tap:
      owner: caffix
      name: homebrew-amass
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/OWASP/Amass/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: caffix
      email: caffix@users.noreply.github.com
    folder: Formula
    homepage: "https://owasp.org/www-project-amass/"
    description: "In-depth Attack Surface Mapping and Asset Discovery"
    test: |
      system "#{bin}/amass --version"
    install: |
      bin.install "amass"
