version: 2
project_name: amass

before:
  hooks:
  - go mod tidy

builds:
  -
    main: ./cmd/amass
    binary: amass
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - resources/config.yaml
      - resources/datasources.yaml

sboms:
  - documents:
      - "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}.bom.json"
    artifacts: binary
    cmd: cyclonedx-gomod
    env:
      - GOOS={{ .Os }}
      - GOARCH={{ .Arch }}
    args: [ "app", "-main", "cmd/amass", "-licenses", "-packages", "-json", "-output", "$document", "." ]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: owasp-amass
    name: amass

homebrew_casks:
  -
    name: amass
    repository:
      owner: owasp-amass
      name: homebrew-amass
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url:
      template: "https://github.com/owasp-amass/amass/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: caffix
      email: caffix@users.noreply.github.com
    homepage: "https://owasp.org/www-project-amass/"
    description: "In-depth Attack Surface Mapping and Asset Discovery"
    caveats: "This is a cask for the Amass tool, which is used for network mapping and attack surface discovery."
    license: "Apache-2.0"
