name: amass
version: '2.7.11'
summary: In-Depth DNS Enumeration and Network Mapping
description: |
  The OWASP Amass tool suite obtains subdomain names by scraping data sources, 
  recursive brute forcing, crawling web archives, permuting/altering names 
  and reverse DNS sweeping. Additionally, Amass uses the IP addresses 
  obtained during resolution to discover associated netblocks and ASNs. All 
  the information is then used to build maps of the target networks.
icon: images/snapcraft_icon.png
grade: stable
confinement: strict


apps:
  amass:
    command: bin/amass
    plugs: [home, network, removable-media]

  maltego:
    command: bin/maltego
    plugs: [home, network, removable-media]
  
  netdomains:
    command: bin/netdomains
    plugs: [home, network, removable-media]
  
  viz:
    command: bin/viz
    plugs: [home, network, removable-media]
  
  db:
    command: bin/db
    plugs: [home, network, removable-media]


parts:
  go:
    source-tag: go1.10

  amass:
    after: [go]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for amass part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go get -u ./...
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass $SNAPCRAFT_PART_INSTALL/bin/amass
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/amass
  
  maltego:
    after: [amass]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for maltego part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go get -u ./...
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass.maltego $SNAPCRAFT_PART_INSTALL/bin/maltego
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/maltego

  netdomains:
    after: [amass]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for netdomains part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go get -u ./...
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass.netdomains $SNAPCRAFT_PART_INSTALL/bin/netdomains
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/netdomains

  viz:
    after: [amass]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for viz part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go get -u ./...
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass.viz $SNAPCRAFT_PART_INSTALL/bin/viz
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/viz
  
  db:
    after: [amass]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for db part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go get -u ./...
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass.db $SNAPCRAFT_PART_INSTALL/bin/db
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/db