name: lint

on:
  push:
  pull_request:

jobs:
  golangci:
    name: Lint
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        go-version: [ "1.24.0" ]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    steps:
      -
        name: setup
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=60m
          only-new-issues: true
